name: CI/CD

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  backend-deploy:
    runs-on: window-latest
    steps:
      # Gradle 실행권한 부여
      - name: Grant execute permission to gradlew
        run: chmod +x ./gradlew

      # Spring boot application 빌드
      - name: Build with gradle
        run: ./gradlew clean bootjar

      # docker image 빌드
      - name: Build docker image
        run: docker build -t dlsqja3436/backendbuild .

      # docker hub 로그인
      - name: Login docker hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # docker hub 퍼블리시
#      - name: Publish to docker hub
#        run: docker push dlsqja3436/backendbuild
        

      # WAS 인스턴스 접속 & 애플리케이션 실행
 #    - name: Connect to WAS & Execute Application
 #       uses: appleboy/ssh-action@v0.1.6
 #       with:
 #         host: ${{ secrets.WAS_HOST }}
 #         username: ${{ secrets.WAS_USERNAME }}
 #         key: ${{ secrets.SSH_KEY }}
 #         port: ${{ secrets.WAS_SSH_PORT }}
 #         script: |
 #           docker stop $(docker ps -a -q) 
 #           docker rm $(docker ps -a -q) 
 #           docker pull <docker_hub_username>/<docker_image_name>
 #           docker run -d -p 8080:8080 --name <container_name> <docker_hub_username>/<docker_image_name>
            
